version: '3'
services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdatabase
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"