name: dotnet-ef-migration-create
description: Create .NET executable migration bundle with EntityFramework
inputs:
  working-directory:
    description: "Directory path of solution root"
    required: true
  migration-name:
    required: true
    description: "Name of the migration to be used in the name of the output file"
  migration-path:
    required: true
    description: Path to the migration .csproj to bundle and execute
  github-token:
    required: false
    description: GitHub Token
    default: ${{ github.token }}

runs:
  using: composite
  steps:
  - name: Setup .NET
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: |
        9.0.x

  - name: .NET Restore Dependencies
    shell: bash
    run: |
      dotnet nuget list source
      if dotnet nuget list source | grep -q "GitHub"; then
        dotnet nuget update source GitHub -u ${{ github.actor }} -p ${{ inputs.github-token }} --store-password-in-clear-text
      fi
      dotnet restore
    working-directory: ${{ inputs.working-directory }}

  - name: .NET Tool Restore
    shell: bash
    run: dotnet tool restore
    working-directory: ${{ inputs.working-directory }}

  - name: Bundle EF Migrations
    shell: bash
    run: dotnet ef migrations bundle --project ${{ inputs.migration-path }} -o ${{ inputs.migration-name }}.exe --verbose -r linux-x64 --configuration Release
    working-directory: ${{ inputs.working-directory }}

  - name: Upload Migrations Artifact
    uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.migration-name }}
      path: ${{ inputs.working-directory }}/${{ inputs.migration-name }}.exe